Implements most EventClass::Execute cases, and functions used by those cases.
TheAssemblyArmada/Chronoshift pull request #104
Opened 2019-07-26 22:25 UTC by tomsons26

2019-07-26 22:28 UTC, tomsons26 commented on src/game/common/globals.cpp
> +int g_FormMove = 0;
not sure about the default values here, there are none in original

2019-07-26 22:29 UTC, tomsons26 commented on src/game/engine/house.cpp
> +ProdFailType HouseClass::Begin_Production(RTTIType rtti, int id)
not sure on the position in the header and cpp for these functions, any specific order they should follow?

2019-07-26 22:30 UTC, tomsons26 commented on src/game/engine/house.h
> +enum ProdFailType
Anything known about this?

2019-08-01 22:10 UTC, OmniBlade requested changes

2019-08-01 22:10 UTC, OmniBlade commented on src/game/engine/building.h
> +    virtual void * Remap_Table();
Formatting issue with placement of * for the pointer, clang-format will fix it.

2019-08-01 22:10 UTC, OmniBlade commented on src/game/engine/foot.cpp
> +    if (target) {
Code style, you should be explict with conditionals, here it should be `if (target != 0)`.

2019-08-01 22:10 UTC, OmniBlade commented on src/game/engine/foot.cpp
> +        for (i = 0; i < NAV_LENGTH && m_NavList[i]; ++i);
And again here, `m_NavList[i] != 0`.

2019-08-01 22:10 UTC, OmniBlade commented on src/game/engine/foot.cpp
> +            if (!i) {
And again here, `i == 0`.

2019-08-01 22:10 UTC, OmniBlade commented on src/game/engine/gameevent.h
> +    GameEventClass(GameEventType type, void *a2, unsigned long a3); // For events: ADDPLAYER
Don't use types that don't have a specific size where a specific size is actually required. Expecially don't use long and unsigned long as they are known to have different sizes on different platforms and architectures. Use uint32_t in place of unsigned long, uint16_t in place of unsigned short and uint8_t in place of unsigned char.

2019-08-01 22:10 UTC, OmniBlade commented on src/game/engine/gameevent.h
> +    // confirmed - TIMING
Are we sure this is a bitfield, looks like two uint16_t's if the bitfield has them as 16 bits?

2019-08-01 22:10 UTC, OmniBlade commented on src/game/engine/gameevent.cpp
> +        // done
You don't need to leave comments saying done in code intended to be final, just leave todos on stuff needing doing and everything else is assumed to be done.

2019-08-16 13:08 UTC, closed without merging