Implements TerrainClass.
TheAssemblyArmada/Chronoshift pull request #129
Opened 2019-10-01 22:40 UTC by tomsons26

2019-10-01 22:43 UTC, CCHyper commented on src/game/engine/terrain.cpp
> +
Formatting. Remove this blank space here.

2019-10-02 09:01 UTC, OmniBlade requested changes

2019-10-02 09:01 UTC, OmniBlade commented on src/game/engine/cell.h
> +    void Clear_Occupant_Bit(CellOccupantEnum bit) { OccupantBit &= bit; }
This needs to be `OccupantBit &= ~bit` to clear a bit.

2019-10-02 09:01 UTC, OmniBlade commented on src/game/engine/terrain.cpp
> +    AnimClass *aptr = new AnimClass(ANIM_BURN_BIG, Coord_Add(Sort_Y(), (unsigned)0xFFB00000));
You don't need the casts to unsigned here, hex values are taken as unsigned by default.

2019-10-02 09:01 UTC, OmniBlade commented on src/game/engine/terrain.cpp
> +    // is Theater_Allowed right?
Looks okay, so you can remove this comment here as it shouldn't end up in the final commit.

2019-10-03 21:30 UTC, OmniBlade submitted a review, later dismissed

2019-10-03 21:55 UTC, OmniBlade submitted a review, later dismissed

2019-10-03 22:15 UTC, OmniBlade approved these changes

2019-10-04 07:19 UTC, merged