Implements a few AircraftClass and Distance, Direction coord functions.
TheAssemblyArmada/Chronoshift pull request #226
Opened 2019-12-21 16:00 UTC by tomsons26

2019-12-23 10:58 UTC, OmniBlade requested changes

2019-12-23 10:58 UTC, OmniBlade commented on src/game/engine/aircraft.cpp
> +        return true;
Return should be 1 here as its not a BOOL return.

2019-12-23 10:58 UTC, OmniBlade commented on src/game/engine/coord.cpp
> +int Distance(cell_t cell1, cell_t cell2)
Where is this function in the original?

2019-12-26 16:06 UTC, tomsons26 commented on src/game/engine/aircraft.cpp
>  void AircraftClass::Movement_AI()
second Physics call should have a != impact_0

2020-01-05 18:06 UTC, ghost approved these changes

2020-01-05 18:07 UTC, merged